removeAnvilXPLimit = true
allowAllEnchantmentCombinations = true
allowAnyEnchantOnAnyItem = true
removeAnvilLevelLimit = true
newAnvilLevelLimit = 255
fairLevelCost = true
removeRepairCostIncrease = true