removeAnvilLimit = true
allowAllEnchantmentCombinations = true
allowAnyEnchantOnAnyItem = true
useGlobalEnchantCap = true
globalEnchantCap = 10
protectionCap = 10
protectionFireCap = 10
protectionBlastCap = 10
protectionProjectileCap = 10
respirationCap = 10
thornsCap = 10
frostWalkerCap = 5
soulSpeedCap = 10
depthStriderCap = 10
featherFallingCap = 10
smiteCap = 10
sharpnessCap = 10
baneOfArthropodsCap = 10
knockbackCap = 5
fireAspectCap = 5
lootingCap = 10
sweepingCap = 10
efficiencyCap = 10
fortuneCap = 10
powerCap = 10
punchCap = 5
lureCap = 10
luckOfTheSeaCap = 10
impalingCap = 10
loyaltyCap = 10
quickChargeCap = 10
piercingCap = 10
unbreakingCap = 10
