# Use Cloth Config mod for the descriptions.
---
modules:
  enchantment: false
fallDamageReduction: 0.5
fallDamageThreshold: 20
speedReductionHorizontal: 1.0
speedReductionVertical: 1.0
modifyPathFinding: true
playerOnly: false
alwaysNotViewBlocking: true
alwaysLeafWalking: true
sounds:
  volume: 1.0
  playerOnly: false
