[mimicSettings]
mimicDifficulty = "MEDIUM"
spawnNaturalMimics = true
naturalMimicSpawnRate = 0.5
allowPetMimics = true
doPetMimicLimit = false
petMimicLimit = 2
abandonedMimicTimer = 5
allowPetMimicLocking = true

[worldGen]
potSpawnChance = 0.15
chestSpawnChance = 0.2
surfaceChestSpawnChance = 0.15
secretMimicChance = 0.15

[chestSettings]
allowChestLocking = true
enableLockedChestOwners = true
